<!DOCTYPE html> <!--OPENING THE HTML-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

</head><!--OPENING THE HEAD ELEMENT-->
<body><!--OPENING THE BODY ELEMENT-->
    <div><!--CREATING THE DIV ELEMENT-->
    <div class="container"><!--CREATING DIV CLASS CONTAINER -->
       <div  class="row">
            <div id="title" class="col-xs-1">
                <img src="images/img.png" alt="Mental Health Forum" /><!--GETTING THE IMAGE FROM IMAGES DIRECTORY-->
                <h1>Mental Health Forum</h1><!--CREATING A HEADER CALLED HEALTH FORUM-->


      </div>
    </div>
    </div>
</body>
</html>
