<!DOCTYPE html>
<html lang="en">
<head><!--STARTING THE HEAD ELEMENT-->
    <title>MENTAL HEALTH</title><!--CREATING THE TITLE-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.css" rel="stylesheet">
        <!-- Bootstrap theme -->
        <link href="/css/bootstrap-theme.css" rel="stylesheet">
        <link href="/css/my-style.css" rel="stylesheet">
        <title>MENTAL HEALTH <?php echo $view->pageTitle ?> </title><!--THE NAME OF THE PAGE-->
    </head><!--OPENING THE HEAD ELEMENT-->
</head><!--CLOSING THE HEAD ELEMENT-->
<body><!--OPENING THE BODY ELEMENT-->

<div class="row">

   </div><!--CLOSING THE DIV ELEMENT-->
<div  class="row">
    <div id="title" class="col-xs-1">
        <img src="images/img.png" alt="Mental Health Forum" /><!--GETTING THE IMAGE FROM IMAGES DIRECTORY-->
        <h1>Mental Health Forum</h1><!--CREATING A HEADER CALLED HEALTH FORUM-->
        <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>
    </div>
    <div class="row">
        <div id="menu" class="col-xs-12 col-sm-12 col-md-1">

            <ul class="nav navbar_default nav-stacked">
                <p2>Welcome to the Mental Health Forum. Please know that you are not alone in your journey. Share your insecurities and fears with millions of people and be someone else's light.</p2>
            </ul>
            <a href="../bridge.php">Click here to see all the posts</a><!--CREATING A LINK TO FORUM PHP-->

        </div>
        <div id="menu2" class="col-xs-12 col-sm-12 col-md-1">


            <p><strong>Sign-in:</strong></p>
            <form name="form" method="post" action="../sign-in.php" ><!--CREATING A NEW FORM-->
                Name:<input type="text" name="user_name" /><!--INPUT TO PUT THE NAME OF THE USER-->
                Password:<input type="password" name="user_password"><!--INPUT TO PUT THE PASSWORD OF THE USER-->
                <input type="submit" name="submit" value="Submit"><!--A SUBMIT BUTTON TO SEND THE DETAILS-->
                <a href="../register.php">Aren't you a member? Register</a><!--A LINK TO REGISTER.PHP TO MAKE USER REGISTER TO THE WEBSITE-->

            </form><!--CLOSING THE FORM-->

        </div>
    </div>
</body><!--CLOSING THE BODY ELEMENT-->


</html><!--CLOSING THE HTML-->


