<!--CREATING A SUBMIT BUTTON TO DIRECT LOG-OUT USERS TO INDEX PAGE-->
<?php require('template/header.phtml');?>
<!DOCTYPE html>  <!--OPENING HTML-->
<html lang="en">
<head><!--OPENING THE HEAD-->
<title>MENTAL HEALTH</title><!--CREATIGN THE TITLE-->
</head><!--CLOSING THE HEAD-->
<body>
<div class="container-fluid">
    <div id="menu" class="col-xs-12 col-sm-12 col-md-12">

        <div class="col-sm-12" ">
        <img src="images/bye.jpg" alt="Mental Health Forum" /><!--GETTING THE IMAGE FROM IMAGES DIREC

  <!--CREATING A DIV CLASS-->
    <form name="submit100" method="POST" action="../index.php"><!--CREATING A FORM-->
    <input type="submit" name="neww2" value="Secure Sign-out" /><!--CREATING A SUBMIT BUTTON TO MAKE USER REACH TO INDEX PAGE-->
    </form><!--CLOSING THE FORM-->
  </div><!--CLOSING DIV-->
</body><!--CLOSING THE BODY ELEMENT-->
</html><!--CLOSING THE HTML-->

