
<!DOCTYPE html><!--OPENING HTML-->
<html lang="en">
<head><!--OPENING HEAD-->
    <title>MENTAL HEALTH</title><!--CREATING THE TITLE-->
</head><!--CLOSING HEAD-->
<body><!--OPENING BODY-->
<form name="form" method="post" action="../index2.php" ><!--CREATING A FORM -->
    <input type="submit" name="SUBMIT" value="HOME"><!--CREATING A SUBMIT BUTTON TO CONNECT USER TO INDEX2.PHP-->
</body><!--CLOSING BODY-->
</html><!--CLOSING HTML-->